/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeeTypesRouteImport } from './routes/fee-types'
import { Route as FeeTypesOverviewRouteImport } from './routes/fee-types-overview'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as AcademicIndexRouteImport } from './routes/academic/index'
import { Route as AcademicLessonNotesRouteImport } from './routes/academic/lesson-notes'
import { Route as AttendanceIndexRouteImport } from './routes/attendance/index'
import { Route as CbtIndexRouteImport } from './routes/cbt/index'
import { Route as EnterpriseIndexRouteImport } from './routes/enterprise/index'
import { Route as FinanceAdjustmentManagementRouteImport } from './routes/finance/adjustment-management'
import { Route as FinanceDashboardRouteImport } from './routes/finance/dashboard'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as TimetableIndexRouteImport } from './routes/timetable/index'
import { Route as TransportIndexRouteImport } from './routes/transport/index'
import { Route as TransportDriversRouteImport } from './routes/transport/drivers'
import { Route as TransportVehiclesRouteImport } from './routes/transport/vehicles'
import { Route as FinanceAdmissionsIndexRouteImport } from './routes/finance/admissions/index'
import { Route as FinanceAdmissionsApplicantProfileRouteImport } from './routes/finance/admissions/applicant-profile'
import { Route as FinanceAdmissionsDecisionsRouteImport } from './routes/finance/admissions/decisions'
import { Route as FinanceAdmissionsEnrolmentRouteImport } from './routes/finance/admissions/enrolment'
import { Route as FinanceAdmissionsExamsRouteImport } from './routes/finance/admissions/exams'
import { Route as FinanceExpenseManagementIndexRouteImport } from './routes/finance/expense-management/index'
import { Route as FinanceFeePostingIndexRouteImport } from './routes/finance/fee-posting/index'
import { Route as FinanceHrPayrollIndexRouteImport } from './routes/finance/hr-payroll/index'
import { Route as FinanceHrPayrollEmployeesRouteImport } from './routes/finance/hr-payroll/employees'
import { Route as FinanceHrPayrollPayrollDashboardRouteImport } from './routes/finance/hr-payroll/payroll-dashboard'
import { Route as FinanceHrPayrollProcessingRouteImport } from './routes/finance/hr-payroll/processing'
import { Route as FinanceHrPayrollSalaryStructureRouteImport } from './routes/finance/hr-payroll/salary-structure'
import { Route as FinanceHrPayrollSalaryTableRouteImport } from './routes/finance/hr-payroll/salary-table'
import { Route as FinanceInvoiceManagementIndexRouteImport } from './routes/finance/invoice-management/index'
import { Route as FinanceOutstandingFeesIndexRouteImport } from './routes/finance/outstanding-fees/index'
import { Route as FinancePayrollManagementIndexRouteImport } from './routes/finance/payroll-management/index'
import { Route as FinanceResultsIndexRouteImport } from './routes/finance/results/index'
import { Route as FinanceWealthLoanIndexRouteImport } from './routes/finance/wealth-loan/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeTypesRoute = FeeTypesRouteImport.update({
  id: '/fee-types',
  path: '/fee-types',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeTypesOverviewRoute = FeeTypesOverviewRouteImport.update({
  id: '/fee-types-overview',
  path: '/fee-types-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicIndexRoute = AcademicIndexRouteImport.update({
  id: '/academic/',
  path: '/academic/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicLessonNotesRoute = AcademicLessonNotesRouteImport.update({
  id: '/academic/lesson-notes',
  path: '/academic/lesson-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceIndexRoute = AttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtIndexRoute = CbtIndexRouteImport.update({
  id: '/cbt/',
  path: '/cbt/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseIndexRoute = EnterpriseIndexRouteImport.update({
  id: '/enterprise/',
  path: '/enterprise/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdjustmentManagementRoute =
  FinanceAdjustmentManagementRouteImport.update({
    id: '/finance/adjustment-management',
    path: '/finance/adjustment-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance/dashboard',
  path: '/finance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableIndexRoute = TimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/transport/',
  path: '/transport/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportDriversRoute = TransportDriversRouteImport.update({
  id: '/transport/drivers',
  path: '/transport/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportVehiclesRoute = TransportVehiclesRouteImport.update({
  id: '/transport/vehicles',
  path: '/transport/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdmissionsIndexRoute = FinanceAdmissionsIndexRouteImport.update({
  id: '/finance/admissions/',
  path: '/finance/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdmissionsApplicantProfileRoute =
  FinanceAdmissionsApplicantProfileRouteImport.update({
    id: '/finance/admissions/applicant-profile',
    path: '/finance/admissions/applicant-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceAdmissionsDecisionsRoute =
  FinanceAdmissionsDecisionsRouteImport.update({
    id: '/finance/admissions/decisions',
    path: '/finance/admissions/decisions',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceAdmissionsEnrolmentRoute =
  FinanceAdmissionsEnrolmentRouteImport.update({
    id: '/finance/admissions/enrolment',
    path: '/finance/admissions/enrolment',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceAdmissionsExamsRoute = FinanceAdmissionsExamsRouteImport.update({
  id: '/finance/admissions/exams',
  path: '/finance/admissions/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceExpenseManagementIndexRoute =
  FinanceExpenseManagementIndexRouteImport.update({
    id: '/finance/expense-management/',
    path: '/finance/expense-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceFeePostingIndexRoute = FinanceFeePostingIndexRouteImport.update({
  id: '/finance/fee-posting/',
  path: '/finance/fee-posting/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceHrPayrollIndexRoute = FinanceHrPayrollIndexRouteImport.update({
  id: '/finance/hr-payroll/',
  path: '/finance/hr-payroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceHrPayrollEmployeesRoute =
  FinanceHrPayrollEmployeesRouteImport.update({
    id: '/finance/hr-payroll/employees',
    path: '/finance/hr-payroll/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceHrPayrollPayrollDashboardRoute =
  FinanceHrPayrollPayrollDashboardRouteImport.update({
    id: '/finance/hr-payroll/payroll-dashboard',
    path: '/finance/hr-payroll/payroll-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceHrPayrollProcessingRoute =
  FinanceHrPayrollProcessingRouteImport.update({
    id: '/finance/hr-payroll/processing',
    path: '/finance/hr-payroll/processing',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceHrPayrollSalaryStructureRoute =
  FinanceHrPayrollSalaryStructureRouteImport.update({
    id: '/finance/hr-payroll/salary-structure',
    path: '/finance/hr-payroll/salary-structure',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceHrPayrollSalaryTableRoute =
  FinanceHrPayrollSalaryTableRouteImport.update({
    id: '/finance/hr-payroll/salary-table',
    path: '/finance/hr-payroll/salary-table',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceInvoiceManagementIndexRoute =
  FinanceInvoiceManagementIndexRouteImport.update({
    id: '/finance/invoice-management/',
    path: '/finance/invoice-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceOutstandingFeesIndexRoute =
  FinanceOutstandingFeesIndexRouteImport.update({
    id: '/finance/outstanding-fees/',
    path: '/finance/outstanding-fees/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancePayrollManagementIndexRoute =
  FinancePayrollManagementIndexRouteImport.update({
    id: '/finance/payroll-management/',
    path: '/finance/payroll-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceResultsIndexRoute = FinanceResultsIndexRouteImport.update({
  id: '/finance/results/',
  path: '/finance/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWealthLoanIndexRoute = FinanceWealthLoanIndexRouteImport.update({
  id: '/finance/wealth-loan/',
  path: '/finance/wealth-loan/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/fee-types-overview': typeof FeeTypesOverviewRoute
  '/students': typeof StudentsRoute
  '/academic/lesson-notes': typeof AcademicLessonNotesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/transport/drivers': typeof TransportDriversRoute
  '/transport/vehicles': typeof TransportVehiclesRoute
  '/academic/': typeof AcademicIndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/cbt/': typeof CbtIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/timetable/': typeof TimetableIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/finance/admissions/applicant-profile': typeof FinanceAdmissionsApplicantProfileRoute
  '/finance/admissions/decisions': typeof FinanceAdmissionsDecisionsRoute
  '/finance/admissions/enrolment': typeof FinanceAdmissionsEnrolmentRoute
  '/finance/admissions/exams': typeof FinanceAdmissionsExamsRoute
  '/finance/hr-payroll/employees': typeof FinanceHrPayrollEmployeesRoute
  '/finance/hr-payroll/payroll-dashboard': typeof FinanceHrPayrollPayrollDashboardRoute
  '/finance/hr-payroll/processing': typeof FinanceHrPayrollProcessingRoute
  '/finance/hr-payroll/salary-structure': typeof FinanceHrPayrollSalaryStructureRoute
  '/finance/hr-payroll/salary-table': typeof FinanceHrPayrollSalaryTableRoute
  '/finance/admissions/': typeof FinanceAdmissionsIndexRoute
  '/finance/expense-management/': typeof FinanceExpenseManagementIndexRoute
  '/finance/fee-posting/': typeof FinanceFeePostingIndexRoute
  '/finance/hr-payroll/': typeof FinanceHrPayrollIndexRoute
  '/finance/invoice-management/': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees/': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management/': typeof FinancePayrollManagementIndexRoute
  '/finance/results/': typeof FinanceResultsIndexRoute
  '/finance/wealth-loan/': typeof FinanceWealthLoanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/fee-types-overview': typeof FeeTypesOverviewRoute
  '/students': typeof StudentsRoute
  '/academic/lesson-notes': typeof AcademicLessonNotesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/transport/drivers': typeof TransportDriversRoute
  '/transport/vehicles': typeof TransportVehiclesRoute
  '/academic': typeof AcademicIndexRoute
  '/attendance': typeof AttendanceIndexRoute
  '/cbt': typeof CbtIndexRoute
  '/enterprise': typeof EnterpriseIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/timetable': typeof TimetableIndexRoute
  '/transport': typeof TransportIndexRoute
  '/finance/admissions/applicant-profile': typeof FinanceAdmissionsApplicantProfileRoute
  '/finance/admissions/decisions': typeof FinanceAdmissionsDecisionsRoute
  '/finance/admissions/enrolment': typeof FinanceAdmissionsEnrolmentRoute
  '/finance/admissions/exams': typeof FinanceAdmissionsExamsRoute
  '/finance/hr-payroll/employees': typeof FinanceHrPayrollEmployeesRoute
  '/finance/hr-payroll/payroll-dashboard': typeof FinanceHrPayrollPayrollDashboardRoute
  '/finance/hr-payroll/processing': typeof FinanceHrPayrollProcessingRoute
  '/finance/hr-payroll/salary-structure': typeof FinanceHrPayrollSalaryStructureRoute
  '/finance/hr-payroll/salary-table': typeof FinanceHrPayrollSalaryTableRoute
  '/finance/admissions': typeof FinanceAdmissionsIndexRoute
  '/finance/expense-management': typeof FinanceExpenseManagementIndexRoute
  '/finance/fee-posting': typeof FinanceFeePostingIndexRoute
  '/finance/hr-payroll': typeof FinanceHrPayrollIndexRoute
  '/finance/invoice-management': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management': typeof FinancePayrollManagementIndexRoute
  '/finance/results': typeof FinanceResultsIndexRoute
  '/finance/wealth-loan': typeof FinanceWealthLoanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/fee-types-overview': typeof FeeTypesOverviewRoute
  '/students': typeof StudentsRoute
  '/academic/lesson-notes': typeof AcademicLessonNotesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/transport/drivers': typeof TransportDriversRoute
  '/transport/vehicles': typeof TransportVehiclesRoute
  '/academic/': typeof AcademicIndexRoute
  '/attendance/': typeof AttendanceIndexRoute
  '/cbt/': typeof CbtIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/timetable/': typeof TimetableIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/finance/admissions/applicant-profile': typeof FinanceAdmissionsApplicantProfileRoute
  '/finance/admissions/decisions': typeof FinanceAdmissionsDecisionsRoute
  '/finance/admissions/enrolment': typeof FinanceAdmissionsEnrolmentRoute
  '/finance/admissions/exams': typeof FinanceAdmissionsExamsRoute
  '/finance/hr-payroll/employees': typeof FinanceHrPayrollEmployeesRoute
  '/finance/hr-payroll/payroll-dashboard': typeof FinanceHrPayrollPayrollDashboardRoute
  '/finance/hr-payroll/processing': typeof FinanceHrPayrollProcessingRoute
  '/finance/hr-payroll/salary-structure': typeof FinanceHrPayrollSalaryStructureRoute
  '/finance/hr-payroll/salary-table': typeof FinanceHrPayrollSalaryTableRoute
  '/finance/admissions/': typeof FinanceAdmissionsIndexRoute
  '/finance/expense-management/': typeof FinanceExpenseManagementIndexRoute
  '/finance/fee-posting/': typeof FinanceFeePostingIndexRoute
  '/finance/hr-payroll/': typeof FinanceHrPayrollIndexRoute
  '/finance/invoice-management/': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees/': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management/': typeof FinancePayrollManagementIndexRoute
  '/finance/results/': typeof FinanceResultsIndexRoute
  '/finance/wealth-loan/': typeof FinanceWealthLoanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fee-types'
    | '/fee-types-overview'
    | '/students'
    | '/academic/lesson-notes'
    | '/finance/adjustment-management'
    | '/finance/dashboard'
    | '/transport/drivers'
    | '/transport/vehicles'
    | '/academic/'
    | '/attendance/'
    | '/cbt/'
    | '/enterprise/'
    | '/teachers/'
    | '/timetable/'
    | '/transport/'
    | '/finance/admissions/applicant-profile'
    | '/finance/admissions/decisions'
    | '/finance/admissions/enrolment'
    | '/finance/admissions/exams'
    | '/finance/hr-payroll/employees'
    | '/finance/hr-payroll/payroll-dashboard'
    | '/finance/hr-payroll/processing'
    | '/finance/hr-payroll/salary-structure'
    | '/finance/hr-payroll/salary-table'
    | '/finance/admissions/'
    | '/finance/expense-management/'
    | '/finance/fee-posting/'
    | '/finance/hr-payroll/'
    | '/finance/invoice-management/'
    | '/finance/outstanding-fees/'
    | '/finance/payroll-management/'
    | '/finance/results/'
    | '/finance/wealth-loan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fee-types'
    | '/fee-types-overview'
    | '/students'
    | '/academic/lesson-notes'
    | '/finance/adjustment-management'
    | '/finance/dashboard'
    | '/transport/drivers'
    | '/transport/vehicles'
    | '/academic'
    | '/attendance'
    | '/cbt'
    | '/enterprise'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/finance/admissions/applicant-profile'
    | '/finance/admissions/decisions'
    | '/finance/admissions/enrolment'
    | '/finance/admissions/exams'
    | '/finance/hr-payroll/employees'
    | '/finance/hr-payroll/payroll-dashboard'
    | '/finance/hr-payroll/processing'
    | '/finance/hr-payroll/salary-structure'
    | '/finance/hr-payroll/salary-table'
    | '/finance/admissions'
    | '/finance/expense-management'
    | '/finance/fee-posting'
    | '/finance/hr-payroll'
    | '/finance/invoice-management'
    | '/finance/outstanding-fees'
    | '/finance/payroll-management'
    | '/finance/results'
    | '/finance/wealth-loan'
  id:
    | '__root__'
    | '/'
    | '/fee-types'
    | '/fee-types-overview'
    | '/students'
    | '/academic/lesson-notes'
    | '/finance/adjustment-management'
    | '/finance/dashboard'
    | '/transport/drivers'
    | '/transport/vehicles'
    | '/academic/'
    | '/attendance/'
    | '/cbt/'
    | '/enterprise/'
    | '/teachers/'
    | '/timetable/'
    | '/transport/'
    | '/finance/admissions/applicant-profile'
    | '/finance/admissions/decisions'
    | '/finance/admissions/enrolment'
    | '/finance/admissions/exams'
    | '/finance/hr-payroll/employees'
    | '/finance/hr-payroll/payroll-dashboard'
    | '/finance/hr-payroll/processing'
    | '/finance/hr-payroll/salary-structure'
    | '/finance/hr-payroll/salary-table'
    | '/finance/admissions/'
    | '/finance/expense-management/'
    | '/finance/fee-posting/'
    | '/finance/hr-payroll/'
    | '/finance/invoice-management/'
    | '/finance/outstanding-fees/'
    | '/finance/payroll-management/'
    | '/finance/results/'
    | '/finance/wealth-loan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeeTypesRoute: typeof FeeTypesRoute
  FeeTypesOverviewRoute: typeof FeeTypesOverviewRoute
  StudentsRoute: typeof StudentsRoute
  AcademicLessonNotesRoute: typeof AcademicLessonNotesRoute
  FinanceAdjustmentManagementRoute: typeof FinanceAdjustmentManagementRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  TransportDriversRoute: typeof TransportDriversRoute
  TransportVehiclesRoute: typeof TransportVehiclesRoute
  AcademicIndexRoute: typeof AcademicIndexRoute
  AttendanceIndexRoute: typeof AttendanceIndexRoute
  CbtIndexRoute: typeof CbtIndexRoute
  EnterpriseIndexRoute: typeof EnterpriseIndexRoute
  TeachersIndexRoute: typeof TeachersIndexRoute
  TimetableIndexRoute: typeof TimetableIndexRoute
  TransportIndexRoute: typeof TransportIndexRoute
  FinanceAdmissionsApplicantProfileRoute: typeof FinanceAdmissionsApplicantProfileRoute
  FinanceAdmissionsDecisionsRoute: typeof FinanceAdmissionsDecisionsRoute
  FinanceAdmissionsEnrolmentRoute: typeof FinanceAdmissionsEnrolmentRoute
  FinanceAdmissionsExamsRoute: typeof FinanceAdmissionsExamsRoute
  FinanceHrPayrollEmployeesRoute: typeof FinanceHrPayrollEmployeesRoute
  FinanceHrPayrollPayrollDashboardRoute: typeof FinanceHrPayrollPayrollDashboardRoute
  FinanceHrPayrollProcessingRoute: typeof FinanceHrPayrollProcessingRoute
  FinanceHrPayrollSalaryStructureRoute: typeof FinanceHrPayrollSalaryStructureRoute
  FinanceHrPayrollSalaryTableRoute: typeof FinanceHrPayrollSalaryTableRoute
  FinanceAdmissionsIndexRoute: typeof FinanceAdmissionsIndexRoute
  FinanceExpenseManagementIndexRoute: typeof FinanceExpenseManagementIndexRoute
  FinanceFeePostingIndexRoute: typeof FinanceFeePostingIndexRoute
  FinanceHrPayrollIndexRoute: typeof FinanceHrPayrollIndexRoute
  FinanceInvoiceManagementIndexRoute: typeof FinanceInvoiceManagementIndexRoute
  FinanceOutstandingFeesIndexRoute: typeof FinanceOutstandingFeesIndexRoute
  FinancePayrollManagementIndexRoute: typeof FinancePayrollManagementIndexRoute
  FinanceResultsIndexRoute: typeof FinanceResultsIndexRoute
  FinanceWealthLoanIndexRoute: typeof FinanceWealthLoanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-types': {
      id: '/fee-types'
      path: '/fee-types'
      fullPath: '/fee-types'
      preLoaderRoute: typeof FeeTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-types-overview': {
      id: '/fee-types-overview'
      path: '/fee-types-overview'
      fullPath: '/fee-types-overview'
      preLoaderRoute: typeof FeeTypesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/': {
      id: '/academic/'
      path: '/academic'
      fullPath: '/academic/'
      preLoaderRoute: typeof AcademicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic/lesson-notes': {
      id: '/academic/lesson-notes'
      path: '/academic/lesson-notes'
      fullPath: '/academic/lesson-notes'
      preLoaderRoute: typeof AcademicLessonNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/': {
      id: '/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt/': {
      id: '/cbt/'
      path: '/cbt'
      fullPath: '/cbt/'
      preLoaderRoute: typeof CbtIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/': {
      id: '/enterprise/'
      path: '/enterprise'
      fullPath: '/enterprise/'
      preLoaderRoute: typeof EnterpriseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/adjustment-management': {
      id: '/finance/adjustment-management'
      path: '/finance/adjustment-management'
      fullPath: '/finance/adjustment-management'
      preLoaderRoute: typeof FinanceAdjustmentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/finance/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/': {
      id: '/timetable/'
      path: '/timetable'
      fullPath: '/timetable/'
      preLoaderRoute: typeof TimetableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/transport'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/drivers': {
      id: '/transport/drivers'
      path: '/transport/drivers'
      fullPath: '/transport/drivers'
      preLoaderRoute: typeof TransportDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/vehicles': {
      id: '/transport/vehicles'
      path: '/transport/vehicles'
      fullPath: '/transport/vehicles'
      preLoaderRoute: typeof TransportVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/admissions/': {
      id: '/finance/admissions/'
      path: '/finance/admissions'
      fullPath: '/finance/admissions/'
      preLoaderRoute: typeof FinanceAdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/admissions/applicant-profile': {
      id: '/finance/admissions/applicant-profile'
      path: '/finance/admissions/applicant-profile'
      fullPath: '/finance/admissions/applicant-profile'
      preLoaderRoute: typeof FinanceAdmissionsApplicantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/admissions/decisions': {
      id: '/finance/admissions/decisions'
      path: '/finance/admissions/decisions'
      fullPath: '/finance/admissions/decisions'
      preLoaderRoute: typeof FinanceAdmissionsDecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/admissions/enrolment': {
      id: '/finance/admissions/enrolment'
      path: '/finance/admissions/enrolment'
      fullPath: '/finance/admissions/enrolment'
      preLoaderRoute: typeof FinanceAdmissionsEnrolmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/admissions/exams': {
      id: '/finance/admissions/exams'
      path: '/finance/admissions/exams'
      fullPath: '/finance/admissions/exams'
      preLoaderRoute: typeof FinanceAdmissionsExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expense-management/': {
      id: '/finance/expense-management/'
      path: '/finance/expense-management'
      fullPath: '/finance/expense-management/'
      preLoaderRoute: typeof FinanceExpenseManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/fee-posting/': {
      id: '/finance/fee-posting/'
      path: '/finance/fee-posting'
      fullPath: '/finance/fee-posting/'
      preLoaderRoute: typeof FinanceFeePostingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/': {
      id: '/finance/hr-payroll/'
      path: '/finance/hr-payroll'
      fullPath: '/finance/hr-payroll/'
      preLoaderRoute: typeof FinanceHrPayrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/employees': {
      id: '/finance/hr-payroll/employees'
      path: '/finance/hr-payroll/employees'
      fullPath: '/finance/hr-payroll/employees'
      preLoaderRoute: typeof FinanceHrPayrollEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/payroll-dashboard': {
      id: '/finance/hr-payroll/payroll-dashboard'
      path: '/finance/hr-payroll/payroll-dashboard'
      fullPath: '/finance/hr-payroll/payroll-dashboard'
      preLoaderRoute: typeof FinanceHrPayrollPayrollDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/processing': {
      id: '/finance/hr-payroll/processing'
      path: '/finance/hr-payroll/processing'
      fullPath: '/finance/hr-payroll/processing'
      preLoaderRoute: typeof FinanceHrPayrollProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/salary-structure': {
      id: '/finance/hr-payroll/salary-structure'
      path: '/finance/hr-payroll/salary-structure'
      fullPath: '/finance/hr-payroll/salary-structure'
      preLoaderRoute: typeof FinanceHrPayrollSalaryStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/hr-payroll/salary-table': {
      id: '/finance/hr-payroll/salary-table'
      path: '/finance/hr-payroll/salary-table'
      fullPath: '/finance/hr-payroll/salary-table'
      preLoaderRoute: typeof FinanceHrPayrollSalaryTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoice-management/': {
      id: '/finance/invoice-management/'
      path: '/finance/invoice-management'
      fullPath: '/finance/invoice-management/'
      preLoaderRoute: typeof FinanceInvoiceManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/outstanding-fees/': {
      id: '/finance/outstanding-fees/'
      path: '/finance/outstanding-fees'
      fullPath: '/finance/outstanding-fees/'
      preLoaderRoute: typeof FinanceOutstandingFeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payroll-management/': {
      id: '/finance/payroll-management/'
      path: '/finance/payroll-management'
      fullPath: '/finance/payroll-management/'
      preLoaderRoute: typeof FinancePayrollManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/results/': {
      id: '/finance/results/'
      path: '/finance/results'
      fullPath: '/finance/results/'
      preLoaderRoute: typeof FinanceResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/wealth-loan/': {
      id: '/finance/wealth-loan/'
      path: '/finance/wealth-loan'
      fullPath: '/finance/wealth-loan/'
      preLoaderRoute: typeof FinanceWealthLoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeeTypesRoute: FeeTypesRoute,
  FeeTypesOverviewRoute: FeeTypesOverviewRoute,
  StudentsRoute: StudentsRoute,
  AcademicLessonNotesRoute: AcademicLessonNotesRoute,
  FinanceAdjustmentManagementRoute: FinanceAdjustmentManagementRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  TransportDriversRoute: TransportDriversRoute,
  TransportVehiclesRoute: TransportVehiclesRoute,
  AcademicIndexRoute: AcademicIndexRoute,
  AttendanceIndexRoute: AttendanceIndexRoute,
  CbtIndexRoute: CbtIndexRoute,
  EnterpriseIndexRoute: EnterpriseIndexRoute,
  TeachersIndexRoute: TeachersIndexRoute,
  TimetableIndexRoute: TimetableIndexRoute,
  TransportIndexRoute: TransportIndexRoute,
  FinanceAdmissionsApplicantProfileRoute:
    FinanceAdmissionsApplicantProfileRoute,
  FinanceAdmissionsDecisionsRoute: FinanceAdmissionsDecisionsRoute,
  FinanceAdmissionsEnrolmentRoute: FinanceAdmissionsEnrolmentRoute,
  FinanceAdmissionsExamsRoute: FinanceAdmissionsExamsRoute,
  FinanceHrPayrollEmployeesRoute: FinanceHrPayrollEmployeesRoute,
  FinanceHrPayrollPayrollDashboardRoute: FinanceHrPayrollPayrollDashboardRoute,
  FinanceHrPayrollProcessingRoute: FinanceHrPayrollProcessingRoute,
  FinanceHrPayrollSalaryStructureRoute: FinanceHrPayrollSalaryStructureRoute,
  FinanceHrPayrollSalaryTableRoute: FinanceHrPayrollSalaryTableRoute,
  FinanceAdmissionsIndexRoute: FinanceAdmissionsIndexRoute,
  FinanceExpenseManagementIndexRoute: FinanceExpenseManagementIndexRoute,
  FinanceFeePostingIndexRoute: FinanceFeePostingIndexRoute,
  FinanceHrPayrollIndexRoute: FinanceHrPayrollIndexRoute,
  FinanceInvoiceManagementIndexRoute: FinanceInvoiceManagementIndexRoute,
  FinanceOutstandingFeesIndexRoute: FinanceOutstandingFeesIndexRoute,
  FinancePayrollManagementIndexRoute: FinancePayrollManagementIndexRoute,
  FinanceResultsIndexRoute: FinanceResultsIndexRoute,
  FinanceWealthLoanIndexRoute: FinanceWealthLoanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
