/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeeTypesRouteImport } from './routes/fee-types'
import { Route as FinanceAdjustmentManagementRouteImport } from './routes/finance/adjustment-management'
import { Route as FinanceExpenseManagementIndexRouteImport } from './routes/finance/expense-management/index'
import { Route as FinanceInvoiceManagementIndexRouteImport } from './routes/finance/invoice-management/index'
import { Route as FinanceOutstandingFeesIndexRouteImport } from './routes/finance/outstanding-fees/index'
import { Route as FinancePayrollManagementIndexRouteImport } from './routes/finance/payroll-management/index'
import { Route as FinanceWealthLoanIndexRouteImport } from './routes/finance/wealth-loan/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeeTypesRoute = FeeTypesRouteImport.update({
  id: '/fee-types',
  path: '/fee-types',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceAdjustmentManagementRoute =
  FinanceAdjustmentManagementRouteImport.update({
    id: '/finance/adjustment-management',
    path: '/finance/adjustment-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceExpenseManagementIndexRoute =
  FinanceExpenseManagementIndexRouteImport.update({
    id: '/finance/expense-management/',
    path: '/finance/expense-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceInvoiceManagementIndexRoute =
  FinanceInvoiceManagementIndexRouteImport.update({
    id: '/finance/invoice-management/',
    path: '/finance/invoice-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceOutstandingFeesIndexRoute =
  FinanceOutstandingFeesIndexRouteImport.update({
    id: '/finance/outstanding-fees/',
    path: '/finance/outstanding-fees/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinancePayrollManagementIndexRoute =
  FinancePayrollManagementIndexRouteImport.update({
    id: '/finance/payroll-management/',
    path: '/finance/payroll-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceWealthLoanIndexRoute = FinanceWealthLoanIndexRouteImport.update({
  id: '/finance/wealth-loan/',
  path: '/finance/wealth-loan/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/expense-management/': typeof FinanceExpenseManagementIndexRoute
  '/finance/invoice-management/': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees/': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management/': typeof FinancePayrollManagementIndexRoute
  '/finance/wealth-loan/': typeof FinanceWealthLoanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/expense-management': typeof FinanceExpenseManagementIndexRoute
  '/finance/invoice-management': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management': typeof FinancePayrollManagementIndexRoute
  '/finance/wealth-loan': typeof FinanceWealthLoanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fee-types': typeof FeeTypesRoute
  '/finance/adjustment-management': typeof FinanceAdjustmentManagementRoute
  '/finance/expense-management/': typeof FinanceExpenseManagementIndexRoute
  '/finance/invoice-management/': typeof FinanceInvoiceManagementIndexRoute
  '/finance/outstanding-fees/': typeof FinanceOutstandingFeesIndexRoute
  '/finance/payroll-management/': typeof FinancePayrollManagementIndexRoute
  '/finance/wealth-loan/': typeof FinanceWealthLoanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fee-types'
    | '/finance/adjustment-management'
    | '/finance/expense-management/'
    | '/finance/invoice-management/'
    | '/finance/outstanding-fees/'
    | '/finance/payroll-management/'
    | '/finance/wealth-loan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fee-types'
    | '/finance/adjustment-management'
    | '/finance/expense-management'
    | '/finance/invoice-management'
    | '/finance/outstanding-fees'
    | '/finance/payroll-management'
    | '/finance/wealth-loan'
  id:
    | '__root__'
    | '/'
    | '/fee-types'
    | '/finance/adjustment-management'
    | '/finance/expense-management/'
    | '/finance/invoice-management/'
    | '/finance/outstanding-fees/'
    | '/finance/payroll-management/'
    | '/finance/wealth-loan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeeTypesRoute: typeof FeeTypesRoute
  FinanceAdjustmentManagementRoute: typeof FinanceAdjustmentManagementRoute
  FinanceExpenseManagementIndexRoute: typeof FinanceExpenseManagementIndexRoute
  FinanceInvoiceManagementIndexRoute: typeof FinanceInvoiceManagementIndexRoute
  FinanceOutstandingFeesIndexRoute: typeof FinanceOutstandingFeesIndexRoute
  FinancePayrollManagementIndexRoute: typeof FinancePayrollManagementIndexRoute
  FinanceWealthLoanIndexRoute: typeof FinanceWealthLoanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fee-types': {
      id: '/fee-types'
      path: '/fee-types'
      fullPath: '/fee-types'
      preLoaderRoute: typeof FeeTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/adjustment-management': {
      id: '/finance/adjustment-management'
      path: '/finance/adjustment-management'
      fullPath: '/finance/adjustment-management'
      preLoaderRoute: typeof FinanceAdjustmentManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/expense-management/': {
      id: '/finance/expense-management/'
      path: '/finance/expense-management'
      fullPath: '/finance/expense-management/'
      preLoaderRoute: typeof FinanceExpenseManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/invoice-management/': {
      id: '/finance/invoice-management/'
      path: '/finance/invoice-management'
      fullPath: '/finance/invoice-management/'
      preLoaderRoute: typeof FinanceInvoiceManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/outstanding-fees/': {
      id: '/finance/outstanding-fees/'
      path: '/finance/outstanding-fees'
      fullPath: '/finance/outstanding-fees/'
      preLoaderRoute: typeof FinanceOutstandingFeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payroll-management/': {
      id: '/finance/payroll-management/'
      path: '/finance/payroll-management'
      fullPath: '/finance/payroll-management/'
      preLoaderRoute: typeof FinancePayrollManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/wealth-loan/': {
      id: '/finance/wealth-loan/'
      path: '/finance/wealth-loan'
      fullPath: '/finance/wealth-loan/'
      preLoaderRoute: typeof FinanceWealthLoanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeeTypesRoute: FeeTypesRoute,
  FinanceAdjustmentManagementRoute: FinanceAdjustmentManagementRoute,
  FinanceExpenseManagementIndexRoute: FinanceExpenseManagementIndexRoute,
  FinanceInvoiceManagementIndexRoute: FinanceInvoiceManagementIndexRoute,
  FinanceOutstandingFeesIndexRoute: FinanceOutstandingFeesIndexRoute,
  FinancePayrollManagementIndexRoute: FinancePayrollManagementIndexRoute,
  FinanceWealthLoanIndexRoute: FinanceWealthLoanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
